LaVague QA CLI
lavague-ai/LaVague pull request #527
Opened 2024-08-02 08:08 UTC by paulpalmieri

- new CLI `lavague-qa`
    - generates pytest files from gherkin test cases (with or without LLMs)
    - handles contexts & token counting
- gherkin examples (4)
- associated docs
    - new side bar section with quicktour, usage, examples
    - update `index.md` (docs Home) and main repo `README.md`
- remove old examples
- update pricing utils token summary
- update `lavague-tests` context loading to handle defaults

2024-08-02 09:25 UTC, lyie28 commented on docs/docs/lavague-qa/examples.md
> +In each of these examples, we'll showcase how LaVague QA can be used to generate tests for critical parts of your websites.
We don't really show how we used LaVague to do this. We just show the feature file and generated file. 

I would do one of the following or similar:
- Add some text about how to run the examples
- Add the command for running the examples with each example so it reads more as a guide
- Add end-to-end notebook examples with the installation, API key and then run and show files using 'cat' so users can really test it live.

2024-08-02 09:27 UTC, lyie28 commented on docs/docs/lavague-qa/examples.md
> +| https://amazon.fr/               | [demo_amazon.feature](https://github.com/lavague-ai/LaVague/blob/main/lavague-qa/features/demo_amazon.feature)       | Tests the Amazon search, cart and cart dele
I changed the URLs here as they were not pointing to lavague-qa/features

2024-08-02 09:32 UTC, lyie28 reviewed
Bug resolved on fresh install :)

2024-08-02 09:53 UTC, lyie28 commented on docs/docs/lavague-qa/usage.md
> +### Flag `--full-llm` or `-llm`
This is not clear for me. Can you re-review this and make sure it's clear what happens for full-llm and what happens for llm & by default which (if either) is used

2024-08-02 09:56 UTC, lyie28 requested changes
- In examples, add command for how to run the examples
- Make the --full-llm --llm flag section a little clearer
- Briefly mention headless/non-headless option in QT as quite important
- Remove no_llm suffix for deafult - only have suffix when --full-llm flag used

2024-08-02 10:02 UTC, lyie28 commented on docs/docs/lavague-qa/usage.md
> +  -h, --headless      Enable headless mode for the browser
I think it's worth adding a line below explaining what this means as it's a very important option + add a quick note in the QT that you can run with headless or non-headless mode

2024-08-06 07:20 UTC, lyie28 approved these changes

2024-08-06 08:44 UTC, adeprez approved these changes

2024-08-06 09:30 UTC, merged